config/routes.rb
Rails.application.routes.draw do
  resources :homepages

  root 'homepages#index'

  get 'portfolio' => 'homepages#homepage'
  get 'about' => 'homepages#about'
  get 'blog' => 'homepages#blog'
  get 'ourteam' => 'homepages#ourteam'
  get 'contact' => 'homepages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  end

  def homepage 
  end

  def about 
  end

  def blog 
  end

  def ourteam 
  end

  def contact 
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_script.html.erb
 <script type="text/javascript">
			$(function() {
				
				var jmpressOpts	= {
					animation		: { transitionDuration : '0.8s' }
				};
				
				
				$( '#jms-slideshow' ).jmslideshow( $.extend( true, { jmpressOpts : jmpressOpts }, {
					autoplay	: true,
					bgColorSpeed: '0.8s',
					arrows		: false
				}));
				
				
				$('.dropdown').hover(function(){
			 		$(this).find('.dropdown-menu').addClass('animated bounceIn');
				},
				function(){
					$(this).find('.dropdown-menu').removeClass('animated bounceIn');
				});
				
			
				//preloader and home animation starter
				$(window).load(function(){
					//$('#pre_loader_mask').hide().remove();
					//start home animation
					
					$('.services').hover(function(){
					$('.services-box-2').addClass('animated fadeInRight');
					}); 
					
					$('.services').hover(function(){
					$(this).find('.services-box-1').addClass('animated fadeInLeft');
					});
					
					$('.process').hover(function(){
					$(this).find('.process-box').addClass('animated bounceIn');
					});
					
					$('.subscribe').hover(function(){
					$(this).find('.input-lg').addClass('animated rotateInDownLeft');
					$(this).find('.btn-effect').addClass('animated rotateIn');
					});
					
					//collapse circular menu after 7 seceond
					// setTimeout(circularMenuConroll,7000);
				});


			$('.bxslider').bxSlider({
			  minSlides: 6,
			  maxSlides: 2,
			  slideWidth: 800,
			  slideMargin: 10
			});
			
			
				
			$( '#dl-menu' ).dlmenu();
				
				
			});
	</script>

app/views/homepages/contact.html.erb
    <div class="container">
    	<div class="header pull-left">
        	
            <!-- <a href="index.html" class="logo"><img src="img/logo.png" alt="logo" /></a> -->
            
            <nav class="navbar navbar-default pull-right" role="navigation">
 
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="<%= root_path %>">Home</a></li>
                  <li><a href="<%= about_path %>">About Us</a></li>
                  <li><a href="<%= blog_path %>">Blog</a></li>
                  <li><a href="<%= portfolio_path %>">Portfolio</a></li>
                  <li><a href="<%= ourteam_path %>">Our Team</a></li>
                  <li><a href="<%= contact_path %>">Contact</a></li>
                </ul>
                
              </div><!-- /.navbar-collapse -->
            </nav>
			
            <div id="dl-menu" class="dl-menuwrapper pull-right">
						<button class="dl-trigger">Open Menu</button>
						<ul class="dl-menu">
							<li>
								<a href="index.html">Home</a>
							</li>
							<li>
								<a href="about.html">About Us</a>
							</li>
							<li>
								<a href="blog.html">Blog</a>
							</li>
                            <li>
								<a href="portfolio.html">Portfolio</a>
							</li>
							<li>
								<a href="#">Dropdown</a>
								<ul class="dl-submenu">
									<li><a href="#">Fine Jewelry</a></li>
									<li><a href="#">Fashion Jewelry</a></li>
									<li><a href="#">Watches</a></li>
									<li>
										<a href="#">Wedding Jewelry</a>
										<ul class="dl-submenu">
											<li><a href="#">Engagement Rings</a></li>
											<li><a href="#">Bridal Sets</a></li>
											<li><a href="#">Women's Wedding Bands</a></li>
											<li><a href="#">Men's Wedding Bands</a></li>
										</ul>
									</li>
								</ul>
							</li>
                            <li>
								<a href="team.html">Our Team</a>
							</li>
                            <li>
								<a href="contact.html">Contact</a>
							</li>
						</ul>
					</div><!-- /dl-menuwrapper -->


        
        </div>
    </div>

	
    <div class="blog contact">
	
    
    <div class="container">
    
    	
    	
        <div class="blog-post pull-left">
        	<div class="blog-header">
            	<div class="ribbon-stitches-bottom"></div>
        		<h1>Contact</h1>
                <div class="ribbon-stitches-bottom"></div>
            </div>
    	
            
            
            
    	</div><!-- End blog-post -->
          
    
    </div><!-- End container -->
    
   </div>
   
   
   
   <div class="gmap map" id="map" data-center="Brugse Heirweg 37 Aartrijke Belgium" data-zoom="15">
                    <address>
                      <div><iframe src="http://maps.google.com/maps/ms?vpsrc=6&amp;ctz=-480&amp;ie=UTF8&amp;msa=0&amp;msid=210840796990572645528.00049770919ccd6759de3&amp;t=m&amp;ll=30.751278,68.203125&amp;spn=84.446143,175.429688&amp;z=2&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="1150" height="300">    </iframe></div>
                    </address>
                  </div><!--End map-->
                  
                  
        <div class="comment">
    
    	<div class="container">
        
        	<form role="form">
            	<div class="row">
                
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="name" class="form-control" id="exampleInputName1" placeholder="Enter name">
                  </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                  <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                  </div>
               </div>
               
              </div><!-- end row -->
              
              
               		<textarea class="form-control" rows="3"></textarea>
               
              
              <button type="submit" class="btn btn-default">Send</button>
            </form>


        
        </div>
    
    </div><!-- End comment -->
   
   
   
	
   <div class="footer">
   
   		<div class="container">
        
        	<div class="row">
            	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Get in touch</h3>
                        
                        <ul>
                        	<li><a href="#">E: support@brightlight.com.bd</a></li>
                            <li><a href="#">P: 0418 281 810</a></li>
                            <li><a href="#">W: www.brightlight.com.bd</a></li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Our Location</h3>
                        
                        <ul>
                        	<li>Bright Light</li>
                            <li>1No. Rode Chandgaon Abashik</li>
                            <li>Chittagong Bangladesh</li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Free Support</h3>
                        
                        <ul>
                        	<li>Call Now</li>
                            <li><a href="#">00800 515151</a></li>
                        </ul>
                        
                    </div>
                </div>
            </div>
        
        </div>
   
   </div><!-- End footer -->

app/views/homepages/homepage.html.erb
    <div class="container">
    	<div class="header pull-left">
        	
            <!-- <a href="index.html" class="logo"><img src="img/logo.png" alt="logo" /></a> -->
            
            <nav class="navbar navbar-default pull-right" role="navigation">
 
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="<%= root_path %>">Home</a></li>
                  <li><a href="<%= about_path %>">About Us</a></li>
                  <li><a href="<%= blog_path %>">Blog</a></li>
                  <li><a href="<%= portfolio_path %>">Portfolio</a></li>
                  <li><a href="<%= ourteam_path %>">Our Team</a></li>
                  <li><a href="<%= contact_path %>">Contact</a></li>
                </ul>
                
              </div><!-- /.navbar-collapse -->
            </nav>
			
            <div id="dl-menu" class="dl-menuwrapper pull-right">
						<button class="dl-trigger">Open Menu</button>
						<ul class="dl-menu">
							<li>
								<a href="index.html">Home</a>
							</li>
							<li>
								<a href="about.html">About Us</a>
							</li>
							<li>
								<a href="blog.html">Blog</a>
							</li>
                            <li>
								<a href="portfolio.html">Portfolio</a>
							</li>
							<li>
								<a href="#">Dropdown</a>
								<ul class="dl-submenu">
									<li><a href="#">Fine Jewelry</a></li>
									<li><a href="#">Fashion Jewelry</a></li>
									<li><a href="#">Watches</a></li>
									<li>
										<a href="#">Wedding Jewelry</a>
										<ul class="dl-submenu">
											<li><a href="#">Engagement Rings</a></li>
											<li><a href="#">Bridal Sets</a></li>
											<li><a href="#">Women's Wedding Bands</a></li>
											<li><a href="#">Men's Wedding Bands</a></li>
										</ul>
									</li>
								</ul>
							</li>
                            <li>
								<a href="team.html">Our Team</a>
							</li>
                            <li>
								<a href="contact.html">Contact</a>
							</li>
						</ul>
					</div><!-- /dl-menuwrapper -->


        
        </div>
    </div>
	
    <div class="blog">
	
    
    <div class="container">
    	
        
        
    	<div class="blog-header pull-left">
            	<div class="ribbon-stitches-bottom"></div>
        		<h1>Portfolio</h1>
                <div class="ribbon-stitches-bottom"></div>
                
                
              <section class="main">
				<div class="wrapper-demo">
					<div id="dd" class="wrapper-dropdown-1" tabindex="1">
						<span>Categories</span>
					    <ul class="dropdown-select portfolioFilter" tabindex="1">
					        <li><a href="#" data-filter="*" class="current">All Categories</a></li>
					        <li><a href="#" data-filter=".people">People</a></li>
                            <li><a href="#" data-filter=".places">Places</a></li>
					        <li><a href="#" data-filter=".food">Food</a></li>
                            <li><a href="#" data-filter=".objects">Objects</a></li>
					    </ul>
					</div>
				​</div>
			</section>
                
       </div>
       
    </div>
    </div><!--blog-->	
           
           
      <div class="container">
        
        <div class="portfolio-container">
        
        <!--<div class="portfolioFilter">
            
                <a href="#" data-filter="*" class="current">All Categories</a>
                <a href="#" data-filter=".people">People</a>
                <a href="#" data-filter=".places">Places</a>
                <a href="#" data-filter=".food">Food</a>
                <a href="#" data-filter=".objects">Objects</a>
            
            </div>-->
            
            
            
            <div class="portfolioContainer">
            
            	<div class=" objects">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog01.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog01.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
                
                <div class="people places">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog02.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog02.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
            
            
            
            	<div class="food">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog03.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog03.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
                
                <div class=" people">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog04.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog04.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
                
                <div class=" objects">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog01.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog01.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
                
                <div class="people places">
                	<div class="portfolio-img view-tenth">
                		<img src="img/blog02.jpg" class="img-responsive"  alt="Responsive image" />
                        <div class="mask">
                            <a id="example7" href="img/blog02.jpg" class="info" title="Cras neque mi, semper at interdum id, dapibus in leo. Suspendisse nunc leo, eleifend sit amet iaculis et, cursus sed turpis."><i class="fa fa-search-plus fa-2x"></i></a>
                            <a href="#" class="link"><i class="fa fa-link fa-2x"></i></a>
                    	</div>
                    </div>
                </div>
                
            
            </div>
            
        </div><!--portfolio-container-->
        
    </div><!-- End container -->
    
   
	
   <div class="footer">
   
   		<div class="container">
        
        	<div class="row">
            	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Get in touch</h3>
                        
                        <ul>
                        	<li><a href="#">E: support@brightlight.com.bd</a></li>
                            <li><a href="#">P: 0418 281 810</a></li>
                            <li><a href="#">W: www.brightlight.com.bd</a></li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Our Location</h3>
                        
                        <ul>
                        	<li>Bright Light</li>
                            <li>1No. Rode Chandgaon Abashik</li>
                            <li>Chittagong Bangladesh</li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Free Support</h3>
                        
                        <ul>
                        	<li>Call Now</li>
                            <li><a href="#">00800 515151</a></li>
                        </ul>
                        
                    </div>
                </div>
            </div>
        
        </div>
   
   </div><!-- End footer -->
<%= render 'port' %>

app/views/homepages/ourteam.html.erb
    <div class="container">
    	<div class="header">
        	
            <!-- <a href="index.html" class="logo"><img src="img/logo.png" alt="logo" /></a> -->
            
            <nav class="navbar navbar-default pull-right" role="navigation">
 
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="<%= root_path %>">Home</a></li>
                  <li><a href="<%= about_path %>">About Us</a></li>
                  <li><a href="<%= blog_path %>">Blog</a></li>
                  <li><a href="<%= portfolio_path %>">Portfolio</a></li>
                  <li><a href="<%= ourteam_path %>">Our Team</a></li>
                  <li><a href="<%= contact_path %>">Contact</a></li>
                </ul>
                
              </div><!-- /.navbar-collapse -->
            </nav>
			
            <div id="dl-menu" class="dl-menuwrapper pull-right">
						<button class="dl-trigger">Open Menu</button>
						<ul class="dl-menu">
							<li>
								<a href="index.html">Home</a>
							</li>
							<li>
								<a href="about.html">About Us</a>
							</li>
							<li>
								<a href="blog.html">Blog</a>
							</li>
                            <li>
								<a href="portfolio.html">Portfolio</a>
							</li>
							<li>
								<a href="#">Dropdown</a>
								<ul class="dl-submenu">
									<li><a href="#">Fine Jewelry</a></li>
									<li><a href="#">Fashion Jewelry</a></li>
									<li><a href="#">Watches</a></li>
									<li>
										<a href="#">Wedding Jewelry</a>
										<ul class="dl-submenu">
											<li><a href="#">Engagement Rings</a></li>
											<li><a href="#">Bridal Sets</a></li>
											<li><a href="#">Women's Wedding Bands</a></li>
											<li><a href="#">Men's Wedding Bands</a></li>
										</ul>
									</li>
								</ul>
							</li>
                            <li>
								<a href="team.html">Our Team</a>
							</li>
                            <li>
								<a href="contact.html">Contact</a>
							</li>
						</ul>
					</div><!-- /dl-menuwrapper -->


        
        </div>
    </div>

	
    <div class="blog blog-dtls">
	
    
    <div class="container">
    	
        <div class="blog-post pull-left">
    	
            <div class="row top80">
            
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                    
                    <div class="r-post-img">
                                <img src="img/blog01.jpg" alt="blog01" />
                                <div class="date-stamp">
                                    <div class="day">02</div>
                                    <div class="month">july</div>
                                    <div class="year">2013</div>
                                </div>
                    </div>
                    
                </div>
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                    <div class="r-post not-right-bdr">
                        <h3><a href="#">Have a peek at what we are writing about</a></h3>
                            
                            <ul class="post-by">
                                <li><a href="#">dona</a></li>
                                <li><a href="#">Demo Posts</a></li>
                            </ul>
                            
                            <p>A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. </p>
                            <p> Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue.
Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Aenean lacinia bibendum nulla sed consectetur. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
							<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Curabitur blandit tempus porttitor. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nullam quis risus eget urna mollis ornare vel eu leo. Cras mattis consectetur purus sit amet fermentum.</p>
                    </div>
                </div>
            
            </div>
    
    	</div><!-- End blog-post -->
        
        
        
    
    </div><!-- End container -->
    
   </div>
   
   
   <div class="comenter">
   
       <div class="container" >
       
           <ul class="media-list">
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" src="img/team02.jpg" alt="...">
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Media heading</h4>
                  <p> Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Aenean lacinia bibendum nulla sed consectetur.</p>
                
                
                	<div class="media">
                      <a class="pull-left" href="#">
                        <img class="media-object" src="img/team01.jpg" alt="...">
                      </a>
                      <div class="media-body">
                        <h4 class="media-heading">Media heading</h4>
                        <p> Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue.</p>
                      </div>
                    </div>

                
                </div>
                
              </li>
              	
            </ul>
            <ul class="media-list">
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" src="img/team02.jpg" alt="...">
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Media heading</h4>
                  <p> Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Nulla vitae elit libero, a pharetra augue.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>
                
              </li>
              	
            </ul>
        
        </div>



	<div class="comment">
    
    	<div class="container">
        
        	<form role="form">
            	<div class="row">
                
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="name" class="form-control" id="exampleInputName1" placeholder="Enter name">
                  </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                  <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                  </div>
               </div>
               
              </div><!-- end row -->
              
              
               		<textarea class="form-control" rows="3"></textarea>
               
              
              <button type="submit" class="btn btn-default">Send</button>
            </form>


        
        </div>
    
    </div><!-- End comment -->
   


	</div><!-- End comenter -->
    
    
	
   <div class="footer">
   
   		<div class="container">
        
        	<div class="row">
            	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Get in touch</h3>
                        
                        <ul>
                        	<li><a href="#">E: support@brightlight.com.bd</a></li>
                            <li><a href="#">P: 0418 281 810</a></li>
                            <li><a href="#">W: www.brightlight.com.bd</a></li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Our Location</h3>
                        
                        <ul>
                        	<li>Bright Light</li>
                            <li>1No. Rode Chandgaon Abashik</li>
                            <li>Chittagong Bangladesh</li>
                        </ul>
                        
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                	<div class="address">
                    	<h3>Free Support</h3>
                        
                        <ul>
                        	<li>Call Now</li>
                            <li><a href="#">00800 515151</a></li>
                        </ul>
                        
                    </div>
                </div>
            </div>
        
        </div>
   
   </div><!-- End footer -->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webtorus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href='http://fonts.googleapis.com/css?family=Oxygen|Lato:300|Open+Sans:300' rel='stylesheet' type='text/css'>

	<link href="css/bootstrap.min.css" rel="stylesheet">
    
    <link href="style.css" rel="stylesheet">
    
    <link href="css/animate-custom.css" rel="stylesheet">
    
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
	
    <!-- jmpress plugin -->
	<script type="text/javascript" src="js/jmpress.min.js"></script>
	<!-- jmslideshow plugin : extends the jmpress plugin -->
	<script type="text/javascript" src="js/jquery.jmslideshow.js"></script>
    
    
    <script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
    
    
    <!-- Responsive menu -->
    
    <script src="js/modernizr.custom.js"></script>
    
    <script src="js/jquery.dlmenu.js"></script>

    <a href="index.html" class="logo"><img src="img/logo.png" alt="logo" /></a>
            

</head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>